---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Ensure apt cache is up to date
  apt:
    update_cache: yes
    cache_valid_time: "{{ cache_timeout }}"
  when:
    - ansible_pkg_mgr == 'apt'

- name: Create horizon dir
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner|default(horizon_system_user_name) }}"
    group: "{{ item.group|default(horizon_system_group_name) }}"
    mode: "{{ item.mode|default('0755') }}"
  with_items:
    - { path: "/etc/pki/tls/certs", owner: "root", group: "root" }
    - { path: "/etc/pki/tls/private", owner: "root", group: "root" }
    - { path: "/var/log/httpd", mode: "2755" }
  when: ansible_pkg_mgr == 'yum'

- name: Create system links
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: "link"
  with_items:
    - { src: "/etc/pki/tls/certs", dest: "/etc/ssl/certs" }
    - { src: "/etc/pki/tls/private", dest: "/etc/ssl/private" }
    - { src: "/var/log/httpd", dest: "/var/log/apache2" }
  when: ansible_pkg_mgr == 'yum'

- name: Install distro packages
  package:
    name: "{{ item }}"
    state: "{{ horizon_package_state }}"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: "{{ horizon_distro_packages }}"

- name: Create developer mode constraint file
  copy:
    dest: "/opt/developer-pip-constraints.txt"
    content: |
      {% for item in horizon_developer_constraints %}
      {{ item }}
      {% endfor %}
  when: horizon_developer_mode | bool

- name: Install requires pip packages
  pip:
    name: "{{ horizon_requires_pip_packages }}"
    state: "{{ horizon_pip_package_state }}"
    extra_args: >-
      {{ (pip_install_upper_constraints is defined) | ternary('--constraint ' + pip_install_upper_constraints | default(''),'') }}
      {{ pip_install_options | default('') }}
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2

- name: Attempt venv download
  get_url:
    url: "{{ horizon_venv_download_url }}"
    dest: "/var/cache/{{ horizon_venv_download_url | basename }}"
    checksum: "sha1:{{ lookup('url', horizon_venv_download_url | replace('tgz', 'checksum')) }}"
  register: horizon_get_venv
  retries: 5
  delay: 5
  until: horizon_get_venv | succeeded
  when: horizon_venv_download | bool

- name: Remove existing venv
  file:
    path: "{{ horizon_bin | dirname }}"
    state: absent
  when: horizon_get_venv | changed

- name: Create horizon venv dir
  file:
    path: "{{ horizon_bin | dirname }}"
    state: directory
    mode: "0755"
  register: horizon_venv_dir
  when: horizon_get_venv | changed

- name: Unarchive pre-built venv
  unarchive:
    src: "/var/cache/{{ horizon_venv_download_url | basename }}"
    dest: "{{ horizon_bin | dirname }}"
    copy: "no"
  when: horizon_get_venv | changed
  notify: Restart apache2

- name: Install pip packages
  pip:
    name: "{{ horizon_pip_packages }}"
    state: "{{ horizon_pip_package_state }}"
    virtualenv: "{{ horizon_bin | dirname }}"
    virtualenv_site_packages: "no"
    extra_args: >-
      {{ horizon_developer_mode | ternary('--constraint /opt/developer-pip-constraints.txt', '') }}
      {{ (pip_install_upper_constraints is defined) | ternary('--constraint ' + pip_install_upper_constraints | default(''),'') }}
      {{ pip_install_options | default('') }}
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  when: horizon_get_venv | failed or horizon_get_venv | skipped
  notify: Restart apache2

- name: Install optional pip packages
  pip:
    name: "{{ horizon_optional_pip_packages }}"
    state: "{{ horizon_pip_package_state }}"
    virtualenv: "{{ horizon_bin | dirname }}"
    virtualenv_site_packages: "no"
    extra_args: >-
      {{ horizon_developer_mode | ternary('--constraint /opt/developer-pip-constraints.txt', '') }}
      {{ (pip_install_upper_constraints is defined) | ternary('--constraint ' + pip_install_upper_constraints | default(''),'') }}
      {{ pip_install_options | default('') }}
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  when: horizon_optional_pip_packages | length > 0

- name: CentOS remove python from path first
  file:
    path:  "{{ horizon_bin | dirname }}/bin/python2.7"
    state: "absent"
  when:
    - ansible_pkg_mgr == 'yum'
    - horizon_get_venv | changed

- name: Update virtualenv path
  command: >
    virtualenv-tools --update-path=auto --reinitialize {{ horizon_bin | dirname }}
  when: horizon_get_venv | changed

- name: Create horizon link for venv
  file:
    src: "{{ horizon_lib_dir | dirname }}/site-packages"
    dest: "{{ horizon_lib_dir }}"
    owner: "{{ horizon_system_user_name }}"
    group: "{{ horizon_system_group_name }}"
    state: "link"

- name: Create static horizon dir
  file:
    path: "{{ item.path }}"
    state: "directory"
    owner: "{{ item.owner|default(horizon_system_user_name) }}"
    group: "{{ item.group|default(horizon_system_group_name) }}"
  with_items:
    - { path: "{{ horizon_lib_dir }}/static", mode: "2755" }
    - { path: "{{ horizon_lib_dir }}/openstack_dashboard", mode: "2755" }
    - { path: "{{ horizon_lib_dir }}/openstack_dashboard/local", mode: "2755" }
    - { path: "{{ horizon_lib_dir }}/openstack_dashboard/local/enabled", mode: "2755" }
