---
- name: Get network configs from OSA servers
  hosts: osa
  tasks:
    - fetch:
        src: /etc/network/interfaces.d/{{ inventory_hostname }}.interfaces.cfg
        dest: backup/test/
        flat: yes
