---
- name: Get network configs from OSA servers
  hosts: srvs
  tasks:
    - fetch:
        src: /etc/network/interfaces.d/{{ ansible_hostname }}.interfaces.cfg
        dest: backup/
        flat: yes
