galaxy_info:
  author: OpenStack-Ansible
  description: Deploy Barbican with OpenStack-Ansible
  company: OpenStack
  license: Apache-2.0
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
      versions:
        - xenial
  galaxy_tags:
    - cloud
    - openstack
    - python
    - barbican

dependencies:
  - pip_install
  - role: apt_package_pinning
    when:
      - ansible_pkg_mgr == 'apt'
  - galera_client

