---
# Copyright 2016, IBM Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Add novalink keys
  apt_key:
    url: "{{ item.url }}"
    state: "{{ item.state }}"
  register: add_nv_keys
  until: add_nv_keys|success
  retries: 5
  delay: 2
  with_items: "{{ novalink_gpg_keys }}"
  tags:
    - novalink-apt-keys

- name: Add novalink repo
  apt_repository:
    repo: "{{ novalink_repo.repo }}"
    state: "{{ novalink_repo.state }}"
    filename:  "{{ novalink_repo.filename | default(omit) }}"
    update_cache: yes
  register: add_nv_repos
  until: add_nv_repos|success
  retries: 5
  delay: 2
  tags:
    - novalink-repo

- name: Register pypowervm module path (venv)
  command: python -c 'import pypowervm; print pypowervm.__file__'
  changed_when: false
  register: pypowervm_module_path
  tags:
    - nova-powervm-libs

- name: Link pypowervm module into the venv
  file:
    src: "{{ pypowervm_module_path.stdout | dirname }}"
    dest: "{{ nova_bin | dirname }}/lib/python2.7/site-packages/pypowervm"
    state: link
    force: "yes"
  tags:
    - nova-powervm-libs

- name: Install pip packages
  pip:
    name: "{{ nova_compute_powervm_pip_packages }}"
    state: "{{ nova_pip_package_state }}"
    virtualenv: "{{ nova_bin | dirname }}"
    virtualenv_site_packages: "no"
    extra_args: "{{ pip_install_options|default('') }}"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  tags:
    - nova-install
    - nova-pip-packages
