---
cidr_networks:
  container: 10.0.23.0/24
  tunnel: 10.0.26.0/24
  storage: 10.0.27.0/24

used_ips:
  - "10.0.23.1,10.0.23.110"
  - "10.0.26.1,10.0.26.110"
  - "10.0.27.1,10.0.27.110"
  - "10.0.28.1,10.0.28.110"

global_overrides:
  internal_lb_vip_address: 10.0.23.11
  external_lb_vip_address: 10.0.23.11
  tunnel_bridge: "br-vxlan"
  management_bridge: "br-mgmt"
  provider_networks:
    - network:
        container_bridge: "br-mgmt"
        container_type: "veth"
        container_interface: "eth1"
        ip_from_q: "container"
        type: "raw"
        group_binds:
          - all_containers
          - hosts
        is_container_address: true
        is_ssh_address: true
    - network:
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth10"
        ip_from_q: "tunnel"
        type: "vxlan"
        range: "1000:2000"
        net_name: "vxlan"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "eth12"
        host_bind_override: "eth12"
        type: "flat"
        net_name: "flat"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "eth11"
        host_bind_override: "eth11"
        type: "vlan"
        range: "10:110,200:300"
        net_name: "vlan"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        ip_from_q: "storage"
        type: "raw"
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute

###
### Infrastructure
###

# galera, memcache, rabbitmq, utility
shared-infra_hosts:
  infra1:
    ip: 10.0.23.105
  infra2:
    ip: 10.0.23.106
  infra3:
    ip: 10.0.23.108

# repository (apt cache, python packages, etc)
repo-infra_hosts:
  infra1:
    ip: 10.0.23.105
  infra2:
    ip: 10.0.23.106
  infra3:
    ip: 10.0.23.108

# load balancer
# Ideally the load balancer should not use the Infrastructure hosts.
# Dedicated hardware is best for improved performance and security.
haproxy_hosts:
  infra1:
    ip: 10.0.23.105
  infra2:
    ip: 10.0.23.106
  infra3:
    ip: 10.0.23.108

# rsyslog server
log_hosts:
  storage2:
    ip: 10.0.23.109

###
### OpenStack
###

# keystone
identity_hosts:
  infra1:
    ip: 10.0.23.105
  infra2:
    ip: 10.0.23.106
  infra3:
    ip: 10.0.23.108

# cinder api services
storage-infra_hosts:
  infra1:
    ip: 10.0.23.105
  infra2:
    ip: 10.0.23.106
  infra3:
    ip: 10.0.23.108

# glance
# The settings here are repeated for each infra host.
# They could instead be applied as global settings in
# user_variables, but are left here to illustrate that
# each container could have different storage targets.
image_hosts:
  infra1:
    ip: 10.0.23.105
    container_vars:
      limit_container_types: glance
      glance_nfs_client:
        - server: "10.0.27.108"
          remote_path: "/images"
          local_path: "/var/lib/glance/images"
          type: "nfs"
          options: "_netdev,auto"
  infra2:
    ip: 10.0.23.106
    container_vars:
      limit_container_types: glance
      glance_nfs_client:
        - server: "10.0.27.108"
          remote_path: "/images"
          local_path: "/var/lib/glance/images"
          type: "nfs"
          options: "_netdev,auto"
  infra3:
    ip: 10.0.23.108
    container_vars:
      limit_container_types: glance
      glance_nfs_client:
        - server: "10.0.27.108"
          remote_path: "/images"
          local_path: "/var/lib/glance/images"
          type: "nfs"
          options: "_netdev,auto"

# nova api, conductor, etc services
compute-infra_hosts:
  infra1:
    ip: 10.0.23.105
  infra2:
    ip: 10.0.23.106
  infra3:
    ip: 10.0.23.108

# heat
orchestration_hosts:
  infra1:
    ip: 10.0.23.105
  infra2:
    ip: 10.0.23.106
  infra3:
    ip: 10.0.23.108

# horizon
dashboard_hosts:
  infra1:
    ip: 10.0.23.105
  infra2:
    ip: 10.0.23.106
  infra3:
    ip: 10.0.23.108

# neutron server, agents (L3, etc)
network_hosts:
  infra1:
    ip: 10.0.23.105
  infra2:
    ip: 10.0.23.106
  infra3:
    ip: 10.0.23.108

# ceilometer (telemetry API)
metering-infra_hosts:
  infra1:
    ip: 10.0.23.105
  infra2:
    ip: 10.0.23.106
  infra3:
    ip: 10.0.23.108

# aodh (telemetry alarm service)
metering-alarm_hosts:
  infra1:
    ip: 10.0.23.105
  infra2:
    ip: 10.0.23.106
  infra3:
    ip: 10.0.23.108

# gnocchi (telemetry metrics storage)
metrics_hosts:
  infra1:
    ip: 10.0.23.105
  infra2:
    ip: 10.0.23.106
  infra3:
    ip: 10.0.23.108

# The infra nodes that will be running the magnum services
magnum-infra_hosts:
  infra1:
    ip: 10.0.23.105
  infra2:
    ip: 10.0.23.106
  infra3:
    ip: 10.0.23.108

# The infra nodes that will be running the trove services
trove-infra_hosts:
  infra1:
    ip: 10.0.23.105
  infra2:
    ip: 10.0.23.106
  infra3:
    ip: 10.0.23.108

# nova hypervisors
compute_hosts:
  compute1:
    ip: 10.0.23.101
  compute2:
    ip: 10.0.23.102
  compute3:
    ip: 10.0.23.103

# ceilometer compute agent (telemetry)
metering-compute_hosts:
  compute1:
    ip: 10.0.23.101
  compute2:
    ip: 10.0.23.102
  compute3:
    ip: 10.0.23.103

# cinder volume hosts (NFS-backed)
# The settings here are repeated for each infra host.
# They could instead be applied as global settings in
# user_variables, but are left here to illustrate that
# each container could have different storage targets.
storage_hosts:
  storage1:
    ip: 10.0.23.107
    container_vars:
      cinder_backends:
        limit_container_types: cinder_volume
        lvm:
          volume_group: cinder-volumes
          volume_driver: cinder.volume.drivers.lvm.LVMVolumeDriver
          volume_backend_name: LVM_iSCSI
          iscsi_ip_address: "10.0.27.107"
  storage2:
    ip: 10.0.23.109
    container_vars:
      cinder_backends:
        limit_container_types: cinder_volume
        lvm:
          volume_group: cinder-volumes
          volume_driver: cinder.volume.drivers.lvm.LVMVolumeDriver
          volume_backend_name: LVM_iSCSI
          iscsi_ip_address: "10.0.27.109"
  infra1:
    ip: 10.0.23.105
    container_vars:
      cinder_backends:
        limit_container_types: cinder_volume
        lvm:
          volume_group: cinder-volumes
          volume_driver: cinder.volume.drivers.lvm.LVMVolumeDriver
          volume_backend_name: LVM_iSCSI
          iscsi_ip_address: "10.0.27.105"
  infra2:
    ip: 10.0.23.106
    container_vars:
      cinder_backends:
        limit_container_types: cinder_volume
        lvm:
          volume_group: cinder-volumes
          volume_driver: cinder.volume.drivers.lvm.LVMVolumeDriver
          volume_backend_name: LVM_iSCSI
          iscsi_ip_address: "10.0.27.106"
