---
galaxy_info:
  author: Donovan Francesco <donovan.francesco@is.co.za>
  description: Deploy Trove with OpenStack Ansible
  company: OpenStack
  license: Apache-2.0
  min_ansible_version: 2.0
  version: 0.1.0
  platforms:
  - name: Ubuntu
    versions:
    - xenial
  galaxy_tags:
   - cloud
   - openstack
   - python
   - trove

dependencies:
  - pip_install
  - role: apt_package_pinning
    when:
      - ansible_pkg_mgr == 'apt'
  - galera_client
  - openstack_openrc
